--Includes all the layout definitions for their easy access
require("layout_definitions.layout_1p_no_cam_4x3")
require("layout_definitions.layout_1p_w_cam_4x3")
require("layout_definitions.layout_2p_4x3")
require("layout_definitions.layout_3p_4x3")
require("layout_definitions.layout_4p_4x3")
require("layout_definitions.layout_1p_no_cam_16x9")
require("layout_definitions.layout_1p_w_cam_16x9")
require("layout_definitions.layout_2p_monkey_ball")
require("layout_definitions.layout_2p_tournament")
require("layout_definitions.layout_fish_out_water")
require("layout_definitions.layout_relay_race")
